### ISSUE TITLE
could not install requirements.txt

### ISSUE THREAD

**Issue by DamienAllonsius** [instant-labs/instant-distance#43]
there is an issue with instant-distance package: 

```
ERROR: Could not find a version that satisfies the requirement instant-distance==0.3.1 (from versions: none)
ERROR: No matching distribution found for instant-distance==0.3.1
```

# how to reproduce the error

## my requirements.txt file:
```
numpy
pytest
nltk
aiohttp==3.8.3
progress==1.6
instant-distance==0.3.1
```
```
python version: 3.9.6
pip version: 23.1.2
MacOS 13.4 (22F66)
```

**Comment by djc** [comment]
Are you on Apple Silicon, by any chance? Is there a reason you can't use 0.3.5?

**Comment by DamienAllonsius** [comment]
yep, Apple Silicon. I just can't install any version of the python lib, 0.3.5 as well

**Comment by djc** [comment]
Yeah -- so far the wheels are generated by GitHub Actions which (at least until recently) didn't have Apple Silicon builders. Let's see if that has changed...

**Comment by DamienAllonsius** [comment]
I trying to install 0.3.1 as per your requirements.txt here:
https://github.com/instant-labs/instant-distance/tree/main/instant-distance-py/examples/translations

**Comment by djc** [comment]
I've uploaded `instant_distance-0.3.5-cp39-cp39-macosx_11_0_arm64.whl`. 0.3.5 should be fully compatible with 0.3.1.

**Comment by DamienAllonsius** [comment]
thanks djc, I get the following warning though


```
pip install instant-distance

Collecting instant-distance
  Downloading instant_distance-0.3.5-cp39-cp39-macosx_11_0_arm64.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.1/311.1 kB 2.8 MB/s eta 0:00:00
WARNING: Error parsing requirements for pybind11: [Errno 2] No such file or directory: '/Users/dallonsius/venvs/T155934243/lib/python3.9/site-packages/pybind11-2.10.4.dist-info/METADATA'
Installing collected packages: instant-distance
Successfully installed instant-distance-0.3.5
```
